### ISSUE TITLE
compare to interledger

### ISSUE THREAD

**Issue by ebuchman** [gnuclear/gnuclear-whitepaper#11]
GnuClear IBC differs from ILP's original whitepaper spec in a few ways...
* Token centricity, as you say.  IBC is also about general packets, but it's also got optional packet confirmations.  IBC also drops the whole thing about hashlocks, because hashlocks are cool but IMO it should really be its own thing.  I could be convinced otherwise.  IBC packet acknowledgement can also handle multihops, although the GnuClear whitepaper doesn't specify it.
* ILP's oracle mode as far as I know doesn't handle oracle-set (validator-set) changes, nor arbitrary weighting.
* IBC is more Tendermint specific in many respects, from the binary format of the vote, to the fact that it's signing block-hashes.
* GnuClear is much more about how everything ties into the hub, which maybe can be viewed as a specific application of ILP's oracle mode.

**Comment by zmanian** [comment]
In my mind, ILP isn't really about scalability. It's about abstracting shared state over bilateral relationships with a simple api. It may be worth talking about these things in #13 or not.

**Comment by jaekwon** [comment]
I added a section on ILP to master
